---
- hosts: all
  become: true
  tasks:
  - name: Update repository index
    apt:
      update_cache: true

  - name: install apache2 package
    apt:
      name: apache2
      state: latest

  - name: Add php support for apach
    apt:
      name: libapache2-mod-php
      state: latest
